services:
    web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:8000"
      env_file:
        - .env-local
      depends_on:
        - db

    db:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=cms
        # logging:
        #   options:
        #     max-size: 10m
        #     max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - /tmp/data:/var/lib/postgresql/data